### PR TITLE
1 FFOX : added short circuit operator

### LINKED ISSUE #1: Breaks in Firefox
```this.target``` in the polyfill is ```undefined``` and breaks in the conditional in line 6 where a new Array is returned only if ```this.target``` is null. In firefox, this.target is undefined so the variable declaration needs a short circuit operator

### PR DESCRIPTION
**Pull request by ezhik1**
Fixes #1 

Allows the polyfill to function in firefox

### CODE REVIEW

**Comment by ezhik1** [comment]
@DieterHolvoet  please have a look

**Comment by DieterHolvoet** [comment]
Thanks for the PR!

**Comment by ezhik1** [comment]
Of course!  Could you also publish the update to npm?

**Comment by DieterHolvoet** [comment]
Done!

**Pull request merged**
